### ISSUE TITLE
RobotJS fails to install (macOS Mojave)

### ISSUE THREAD

**Issue by theLMGN** [octalmage/robotjs#496] opened 2019-07-24 20:12 UTC
## Expected Behavior
RobotJS compiles and installs.

## Current Behavior
It fails.
```
$ npm i robotjs

> robotjs@0.5.1 install /Users/thelmgn/Documents/arduino remote/node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.7.0 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
../src/robotjs.cc:63:39: error: too few arguments to function call, single argument 'context' was not specified
        const size_t x = info[0]->Int32Value();
                         ~~~~~~~~~~~~~~~~~~~ ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2576:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:64:39: error: too few arguments to function call, single argument 'context' was not specified
        const size_t y = info[1]->Int32Value();
                         ~~~~~~~~~~~~~~~~~~~ ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2576:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:97:33: error: too few arguments to function call, single argument 'context' was not specified
        size_t x = info[0]->Int32Value();
                   ~~~~~~~~~~~~~~~~~~~ ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2576:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:98:33: error: too few arguments to function call, single argument 'context' was not specified
        size_t y = info[1]->Int32Value();
                   ~~~~~~~~~~~~~~~~~~~ ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2576:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:114:33: error: too few arguments to function call, single argument 'context' was not specified
        size_t x = info[0]->Int32Value();
                   ~~~~~~~~~~~~~~~~~~~ ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2576:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:115:33: error: too few arguments to function call, single argument 'context' was not specified
        size_t y = info[1]->Int32Value();
                   ~~~~~~~~~~~~~~~~~~~ ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2576:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:143:39: error: no matching member function for call to 'ToString'
                v8::String::Utf8Value bstr(info[0]->ToString());
                                           ~~~~~~~~~^~~~~~~~
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2535:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2551:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<String> ToString(Isolate* isolate) const);
                              ^
../src/robotjs.cc:159:22: error: no matching member function for call to 'BooleanValue'
                doubleC = info[1]->BooleanValue();
                          ~~~~~~~~~^~~~~~~~~~~~
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2566:8: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2569:51: note: candidate function not viable: requires single argument 'context', but no arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../src/robotjs.cc:239:35: error: too few arguments to function call, single argument 'context' was not specified
        mouseDelay = info[0]->Int32Value();
                     ~~~~~~~~~~~~~~~~~~~ ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2576:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:251:30: error: too few arguments to function call, single argument 'context' was not specified
        int x = info[0]->Int32Value();
                ~~~~~~~~~~~~~~~~~~~ ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2576:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:252:30: error: too few arguments to function call, single argument 'context' was not specified
        int y = info[1]->Int32Value();
                ~~~~~~~~~~~~~~~~~~~ ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:2576:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/robotjs.cc:418:44: error: expected '(' for function-style cast or type construction
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                  ~~~~~~~~~^
../src/robotjs.cc:418:28: error: no member named 'Handle' in namespace 'v8'
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                       ~~~~^
../src/robotjs.cc:418:46: error: use of undeclared identifier 'value'; did you mean 'False'?
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                             ^~~~~
                                             False
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:304:25: note: 'False' declared here
  friend Local<Boolean> False(Isolate* isolate);
                        ^
../src/robotjs.cc:418:53: error: unexpected type name 'MMKeyFlags': expected expression
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                                    ^
../src/robotjs.cc:418:65: error: use of undeclared identifier 'flags'
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                                                ^
../src/robotjs.cc:418:71: error: expected ';' after top level declarator
int GetFlagsFromString(v8::Handle<v8::Value> value, MMKeyFlags* flags)
                                                                      ^
                                                                      ;
../src/robotjs.cc:762:1: error: unknown type name 'BMP'
BMP buildBMP(Local<Object> info)
^
../src/robotjs.cc:766:2: error: unknown type name 'BMP'
        BMP img;
        ^
../src/robotjs.cc:768:19: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
        img.width = obj->Get(Nan::New("width").ToLocalChecked())->Uint32Value();
                         ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8.h:3419:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/thelmgn/.node-gyp/12.7.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:266:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/thelmgn/Documents/arduino remote/node_modules/robotjs
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN arduino-remote@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thelmgn/.npm/_logs/2019-07-24T20_08_38_859Z-debug.log
```

## Steps to Reproduce (for bugs)

1. `npm i robotjs`

## Your Environment

* RobotJS version: 0.5.1
* Node.js version: v12.7.0
* npm version: v6.10.0
* Operating System: macOS Mojave (10.14.5 (18F132))

**Comment by JagoGyselinck** [comment] 2019-07-30 12:10
Duplicate of #482

**Closed** 2019-08-07 11:50 UTC
