### ISSUE TITLE
typeString() and keyTap() slow even with 1ms delay

### ISSUE THREAD

**Issue by TreeOfSelf** [octalmage/robotjs#530] opened 2019-12-10 00:30 UTC
`robot.setKeyboardDelay(1);
robot.typeString('*cough');
`

is much slower than having *cough set in the clipboard and doing

`	robot.keyToggle('control','down')
	robot.keyTap('v');`

I think it could be the blocking nature of the module, and the fact that my PC is very slow.

**Comment by Bryley** [comment] 2019-12-26 07:46
I'm having the same issue too. I also notice I'm getting `Invalid MIT-MAGIC-COOKIE-1 key` in the terminal as soon as the typing occurs.

**Comment by nasser** [comment] 2020-01-01 17:12
I am seeing the same thing. Typing 'Hello World' takes around 2.4 seconds where I would expect it to take around 11ms with a 1ms delay set with `setKeyboardDelay`.

```js
// test.js
var robot = require("robotjs");
robot.setKeyboardDelay(1)
robot.typeString("Hello World");
```

```
$ time node test.js 
Hello World
real    0m2.429s
user    0m0.025s
sys     0m0.017s
```

I am on Linux if that makes a difference.

**Comment by Kyusung4698** [comment] 2020-01-04 15:48
https://github.com/octalmage/robotjs/blob/master/src/keypress.c#L17
```c
#if defined(IS_WINDOWS)
	#define WIN32_KEY_EVENT_WAIT(key, flags) \
		(win32KeyEvent(key, flags), Sleep(DEADBEEF_RANDRANGE(63, 125)))
#elif defined(USE_X11)
	#define X_KEY_EVENT(display, key, is_press) \
		(XTestFakeKeyEvent(display, \
		                   XKeysymToKeycode(display, key), \
		                   is_press, CurrentTime), \
		 XSync(display, false))
	#define X_KEY_EVENT_WAIT(display, key, is_press) \
		(X_KEY_EVENT(display, key, is_press), \
		 microsleep(DEADBEEF_UNIFORM(62.5, 125.0)))
#endif
```

tapKey uses toggleKeyCode which calls WIN32_KEY_EVENT_WAIT once for a key and twice for a key with modifiers and therefore it can generate an additional delay of max 250ms.
i dunno why there is a extra sleep call. i [forked the repository](https://github.com/Kyusung4698/robotjs/commit/731f70686c863de51649521ea207bb60aa7511a3) and removed it and it works fine.
< 2ms per call instead of 300ms +

**Comment by nasser** [comment] 2020-01-07 14:19
Interesting, that doesn't explain the delays on Linux though, which I would expect to correspond to the block under `defined(USE_X11)` . Could it be the `XSync` line?

**Comment by Kyusung4698** [comment] 2020-01-07 22:07
It uses X_KEY_EVENT_WAIT on linux and therefore the sleep is the same as on windows.

**Comment by nasser** [comment] 2020-01-08 13:13
ah gotcha, looking at the file now. this seems deliberate -- i wonder what its trying to achieve?

i suppose a next step would be for me to fork and compile the repo with that code edited out and see what effect it has. i will give that a shot when i can.

**Comment by adamup928** [comment] 2020-01-10 15:22
Just edited out the delay and recompiled; everything seems to work as expected again.

**Comment by Sentero-esp12** [comment] 2020-01-17 00:13
Could you please share a modified file? And is it for Linux too?

**Comment by Sentero-esp12** [comment] 2020-01-17 11:11
This fixed the delay for Linux as well:
https://github.com/Sentero-esp12/robotjs/commit/b3fdada5719c38abc18e373b6ba9f3c5e3f52745

**Comment by ricardopolo** [comment] 2020-03-05 05:08
@Kyusung4698 would you make a PR with this change?
Thank you!!!!

**Comment by tillbaks** [comment] 2020-03-05 06:48
A problem arises when you remove the delay on windows is that button presses on same button can get lost. Example you send 11-222-333 with typestring and only see 1-2-3 on screen. 

Solution is quite simple (Just send a keyup event as well): https://github.com/tillbaks/robotjs/commit/0ac7be2878b887e25485311846dbe2b3411f384a

**Comment by rayfoss** [comment] 2020-03-31 14:14
- Anybody know what the MIT-MAGIC-COOKIE-1 thing is?
- The title should be changed to "Linux/Windows"... Im having the issue in Ubuntu LTS
- The master branch silently breaks typing on linux all together! :(
  - Makes it hard to test #560 if master is broken
- #530 should be closed. duplicate
- #559 should be closed as it doesn't address the root cause. That said, removing deadbeef is a quick fix for linux... it does break the sleep option and makes it type super fast.

**Comment by ricardopolo** [comment] 2020-03-31 18:59
@rayfoss do you think super fast is a downside?
In our case we are creating a remote desktop application and using robotjs for automate the user interaction, so typing as fast as possible (as similar to remote endpoint) is crucial for us.

**Comment by rayfoss** [comment] 2020-04-01 00:21
@ricardopolo sometimes I want to hide the fact that I'm using a bot. Typing impossibly fast is a dead giveaway. That said, typeString isn't designed to be slow... typeStringDelayed is. Everything looks great with #560 ...

**Closed** 2020-04-22 13:27 UTC

**Comment by ZhangSanDeHao** [comment] 2020-08-21 07:56
```javascript

// 输入字符
async function string(str) {
  await copyString(str);
  await tap('v', 'control');
  await sleep(20);
}

**Comment by lucasguaru** [comment] 2020-12-30 11:24
> https://github.com/octalmage/robotjs/blob/master/src/keypress.c#L17
> 
> ```c
> #if defined(IS_WINDOWS)
> 	#define WIN32_KEY_EVENT_WAIT(key, flags) \
> 		(win32KeyEvent(key, flags), Sleep(DEADBEEF_RANDRANGE(63, 125)))
> #elif defined(USE_X11)
> 	#define X_KEY_EVENT(display, key, is_press) \
> 		(XTestFakeKeyEvent(display, \
> 		                   XKeysymToKeycode(display, key), \
> 		                   is_press, CurrentTime), \
> 		 XSync(display, false))
> 	#define X_KEY_EVENT_WAIT(display, key, is_press) \
> 		(X_KEY_EVENT(display, key, is_press), \
> 		 microsleep(DEADBEEF_UNIFORM(62.5, 125.0)))
> #endif
> ```
> 
> tapKey uses toggleKeyCode which calls WIN32_KEY_EVENT_WAIT once for a key and twice for a key with modifiers and therefore it can generate an additional delay of max 250ms.
> i dunno why there is a extra sleep call. i [forked the repository](https://github.com/Kyusung4698/robotjs/commit/731f70686c863de51649521ea207bb60aa7511a3) and removed it and it works fine.
> < 2ms per call instead of 300ms +

Is there any way I can make this locally? I'm using the latest version (0.6.0) but it still occurs.

**Comment by H-s-O** [comment] 2021-01-02 02:21
@lucasguaru You could always try to patch it with [patch-package](https://www.npmjs.com/package/patch-package) if you need to have it fixed locally.

**Comment by jameshfisher** [comment] 2021-01-07 10:39
@octalmage would you accept a PR that made this configurable? E.g.:

```
robot.setUseRandomDelay(false);  // New option; defaults to true (backwards compat)
```

The implementation being something like

```
	#define WIN32_KEY_EVENT_WAIT(key, flags) \
		(win32KeyEvent(key, flags), Sleep(useRandomDelay ? DEADBEEF_RANDRANGE(63, 125) : 0))
```

If so I can work on it.

**Comment by jameshfisher** [comment] 2021-01-07 11:00
It's worth noting that this "random delay" behavior is not present/implemented on macOS/OSX. It's only present on Windows and Linux, from the looks of the code (and comments above).

**Comment by jameshfisher** [comment] 2021-01-07 11:04
Oh! I see this is actually fixed on `master` (via https://github.com/octalmage/robotjs/pull/560). But @octalmage @octapodia it's not updated on npm?

**Comment by lucasguaru** [comment] 2021-01-07 11:06
Is this project still active? Why is this not fixed in the final version?

**Comment by jameshfisher** [comment] 2021-01-07 11:24
Note to others with this issue, installing directly from git seems to work:

```
npm install git+https://github.com/octalmage/robotjs.git
```

(This is undesirable because, in general, the git source is not necessarily the same as the npm package contents. Also because it doesn't specify a version constraint. But it's better than nothing and in this case seems to work ...)

**Comment by michelvermeulen** [comment] 2021-03-28 19:29
Hey guys,

Thanks for the workaround, I tried on my end to install from GH but I get an error I didn't get with the NPM version:

```
 The module robotjs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 85
```

I did try `npm rebuild`, `npm rebuild --build-from-source` and  `npm rebuild robotjs --update-binary` but same thing.

Any idea what I'm doing wrong?

**Comment by MLateralus** [comment] 2021-06-10 08:18
Hello, 

Removing the Sleep entirely causes the typeString to sometimes skip double occurances, in the words like:
"Annoying" -> "Anoying" or "soon" -> "son"

I found that changing the values to border Sleep(DEADBEEF_RANDRANGE(11, 22) resolves this issue of skipping repeated chars on windows.

**Comment by wimurk** [comment] 2022-02-11 14:52
Is this still a thing? I just installed the package and the typing is extreemly slow.

**Comment by AcidTr** [comment] 2022-02-15 12:50
We were struggling with keyTap method that usually takes 250ms synchronous to tap a single key. We solved it installing directly from github repo as this response from @jameshfisher . 

> ### [<img alt="@jameshfisher" width="20" height="20" src="https://avatars.githubusercontent.com/u/166966?s=60&amp;u=b78059abca798fbce8c9da4f6ddfb72ea03b20bb&amp;v=4">](/jameshfisher) ** [jameshfisher](/jameshfisher) **

We did one extra step to make it work: Delete node_modules and install again. After installing directly from Github (using yarn), the package.json was like: 

```

"dependencies": {
   "undefined": "https://github.com/octalmage/robotjs"
   }

```

Make sure to change the dependecy from undefined to robotjs


```

"dependencies": {
   "robotjs": "https://github.com/octalmage/robotjs"
   }

```

Now it takes less than 30ms to execute the keyTap method.

**Comment by fttx** [comment] 2022-07-19 10:32
As said @MLateralus the code on the master branch skips repeated characters.  Words such as `Soon` are typed like this: `Son`.

Using this fix `Sleep(DEADBEEF_RANDRANGE(11, 22)` didn't work for me.  
Does anyone have an idea why?

**Comment by wimurk** [comment] 2022-07-25 13:11
@fttx nope. i searched for weeks until i swapped to this package 
https://nutjs.dev/

The temporary fix i used was copy text and paste.

**Comment by veptune** [comment] 2024-05-01 11:13
Hello,

I have exactly the same issue, I have install robotjs with npm install robotjs

Because this issue was found long time ago, I thought it has been fixed in all packages and that I did not need to install it via : npm install git+https://github.com/octalmage/robotjs.git

Do I still have to install it with the package from github ? Is there still a difference between the 2 packages?

I can't install the package from github  :

https://stackoverflow.com/questions/78413415/gyp-or-python-error-when-installing-robotjs-with-npm-install-githttps-githu

but npm install robotjs works fine

Thanks anyway
