### ISSUE TITLE
The robotjs installation failed

### ISSUE THREAD

**Issue by iziziziziziz** [octalmage/robotjs#517] opened 2019-11-07 15:26 UTC
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  robotjs.cc
  win_delay_load_hook.cc
e:\workspace\client\node_modules\robotjs\src\os.h(26): warning C4005: “STRICT”: 宏重定义 (编译源文件 ..\src\robotjs.cc) [E:\workspace\client\node_modul
es\robotjs
\build\robotjs.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\minwindef.h(23): note: 参见“STRICT”的前一个定义 (编译源文件 ..\src\robotjs.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(63): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_module
s\robotjs
\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(63): error C2789: “x”: 必须初始化常量限定类型的对象 [E:\workspace\client\node_modules\robotjs\b
uild\robotjs.vc
xproj]
  e:\workspace\client\node_modules\robotjs\src\robotjs.cc(63): note: 参见“x”的声明
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(64): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_module
s\robotjs
\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(64): error C2789: “y”: 必须初始化常量限定类型的对象 [E:\workspace\client\node_modules\robotjs\b
uild\robotjs.vc
xproj]
  e:\workspace\client\node_modules\robotjs\src\robotjs.cc(64): note: 参见“y”的声明
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(97): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_module
s\robotjs
\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(98): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_module
s\robotjs
\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(114): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(115): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(143): error C2661: “v8::Value::ToString”: 没有重载函数接受 0 个参数 [E:\workspace\client\node_m
odules\robot
js\build\robotjs.vcxproj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(143): error C2512: “v8::String::Utf8Value::Utf8Value”: 没有合适的默认构造函数可用 [E:\workspace
\client\node_m
odules\robotjs\build\robotjs.vcxproj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(159): error C2661: “v8::Value::BooleanValue”: 没有重载函数接受 0 个参数 [E:\workspace\client\no
de_modules\r
obotjs\build\robotjs.vcxproj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(239): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(251): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(252): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(418): error C2039: “Handle”: 不是“v8”的成员 [E:\workspace\client\node_modules\robotjs\build\r
obotjs.v
cxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8-platform.h(16): note: 参见“v8”的声明
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(418): error C2065: “Handle”: 未声明的标识符 [E:\workspace\client\node_modules\robotjs\build\rob
otjs.vcx
proj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(418): error C2275: “v8::Value”: 将此类型用作表达式非法 [E:\workspace\client\node_modules\robotj
s\build\robo
tjs.vcxproj]
  e:\workspace\client\node_modules\robotjs\src\robotjs.cc(418): note: 参见“v8::Value”的声明
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(418): error C2065: “value”: 未声明的标识符 [E:\workspace\client\node_modules\robotjs\build\robo
tjs.vcxp
roj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(418): error C2065: “flags”: 未声明的标识符 [E:\workspace\client\node_modules\robotjs\build\robo
tjs.vcxp
roj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(418): error C2275: “MMKeyFlags”: 将此类型用作表达式非法 [E:\workspace\client\node_modules\robot
js\build\rob
otjs.vcxproj]
  e:\workspace\client\node_modules\robotjs\src\keypress.h(50): note: 参见“MMKeyFlags”的声明
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(419): error C2448: “GetFlagsFromString”: 函数样式初始值设定项类似函数定义 [E:\workspace\client\
node_modules\robo
tjs\build\robotjs.vcxproj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(424): error C2039: “Handle”: 不是“v8”的成员 [E:\workspace\client\node_modules\robotjs\build\r
obotjs.v
cxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8-platform.h(16): note: 参见“v8”的声明
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(424): error C2065: “Handle”: 未声明的标识符 [E:\workspace\client\node_modules\robotjs\build\rob
otjs.vcx
proj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(424): error C2275: “v8::Value”: 将此类型用作表达式非法 [E:\workspace\client\node_modules\robotj
s\build\robo
tjs.vcxproj]
  e:\workspace\client\node_modules\robotjs\src\robotjs.cc(424): note: 参见“v8::Value”的声明
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(424): error C2065: “value”: 未声明的标识符 [E:\workspace\client\node_modules\robotjs\build\robo
tjs.vcxp
roj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(424): error C2065: “flags”: 未声明的标识符 [E:\workspace\client\node_modules\robotjs\build\robo
tjs.vcxp
roj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(424): error C2275: “MMKeyFlags”: 将此类型用作表达式非法 [E:\workspace\client\node_modules\robot
js\build\rob
otjs.vcxproj]
  e:\workspace\client\node_modules\robotjs\src\keypress.h(50): note: 参见“MMKeyFlags”的声明
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(425): error C2448: “GetFlagsFromValue”: 函数样式初始值设定项类似函数定义 [E:\workspace\client\n
ode_modules\robot
js\build\robotjs.vcxproj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(457): error C2661: “v8::Value::ToString”: 没有重载函数接受 0 个参数 [E:\workspace\client\node_m
odules\robot
js\build\robotjs.vcxproj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(457): error C2512: “v8::String::Utf8Value::Utf8Value”: 没有合适的默认构造函数可用 [E:\workspace
\client\node_m
odules\robotjs\build\robotjs.vcxproj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(463): error C2064: 项不会计算为接受 2 个参数的函数 [E:\workspace\client\node_modules\robotjs\buil
d\robotjs.vcx
proj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(515): error C2064: 项不会计算为接受 2 个参数的函数 [E:\workspace\client\node_modules\robotjs\buil
d\robotjs.vcx
proj]
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(589): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(603): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(639): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(640): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(708): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(709): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(710): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(711): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(768): error C2660: “v8::Value::Uint32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modu
les\robot
js\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: 参见“v8::Value::Uint32Value”的声明 (编译源文件 ..\src\robo
tjs.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(769): error C2660: “v8::Value::Uint32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modu
les\robot
js\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: 参见“v8::Value::Uint32Value”的声明 (编译源文件 ..\src\robo
tjs.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(770): error C2660: “v8::Value::Uint32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modu
les\robot
js\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: 参见“v8::Value::Uint32Value”的声明 (编译源文件 ..\src\robo
tjs.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(771): error C2660: “v8::Value::Uint32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modu
les\robot
js\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: 参见“v8::Value::Uint32Value”的声明 (编译源文件 ..\src\robo
tjs.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(772): error C2660: “v8::Value::Uint32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modu
les\robot
js\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2611): note: 参见“v8::Value::Uint32Value”的声明 (编译源文件 ..\src\robo
tjs.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(774): warning C4996: 'v8::Object::Get': 被声明为已否决 [E:\workspace\client\node_modules\robotjs\
build\
robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(3457): note: 参见“v8::Object::Get”的声明
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(788): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
e:\workspace\client\node_modules\robotjs\src\robotjs.cc(789): error C2660: “v8::Value::Int32Value”: 函数不接受 0 个参数 [E:\workspace\client\node_modul
es\robotj
s\build\robotjs.vcxproj]
  c:\users\administrator\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2613): note: 参见“v8::Value::Int32Value”的声明 (编译源文件 ..\src\robot
js.cc)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

gyp ERR! cwd E:\workspace\client\node_modules\robotjs
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN client@1.0.0 No description
npm WARN client@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by markogresak** [comment] 2019-11-09 15:12
This is a duplicate of #514.

**Comment by oktapodia** [comment] 2019-11-24 17:55
Closing as it is a duplicate.

**Closed by oktapodia** 2019-11-24 17:55 UTC
Labels: duplicate
