### ISSUE TITLE
Printing UTF-8 Characters with accents

### ISSUE THREAD

**Issue by bernatbombi** [octalmage/robotjs#16] opened 2015-03-04 10:43 UTC
Hi,

when you try to typeString a character with accents, the returned string is not correct.

For example, when I try `robot.typeString('à')` it returns `ￃﾠ`.

The same happens when I try to print an `ñ`, it returns `ￃﾱ`.

Is there a way to make this work?

**Comment by octalmage** [comment] 2015-03-06 07:06
There's always a way! Thanks for bringing this to my attention. I'll look into it when I get some time.

**Comment by octalmage** [comment] 2015-07-28 15:59
I looked into this for a few minutes and I believe the issue is in keypress.c. I'm curious if this is an issue on Windows though. I'll update when I have more time to test.

**Comment by Nikersify** [comment] 2015-07-28 20:57
`robot.typeString('!@#$%^&*()')` returns `1234567890` on windows, probably related.

**Comment by octalmage** [comment] 2015-07-28 21:53
Uh oh! That's silly.

**Comment by Deltatiger** [comment] 2015-07-29 03:37
I will check this out on windows when I have the time.

**Comment by octalmage** [comment] 2015-12-29 09:23
The Windows issue mentioned by @Nikersify was fixed in #110.

**Comment by alice0meta** [comment] 2016-11-23 03:38
https://github.com/octalmage/robotjs/blob/master/src/keypress.c#L224 typeString prints one byte at a time; probably that's a utf8 string & any characters outside of ascii take more than one byte; it needs to handle this. I'd send a pull request but I don't know enough C to write C.

**Comment by giacomocerquone** [comment] 2016-11-29 21:43
Same problems here!

**Comment by amoshydra** [comment] 2016-12-22 16:59
Hi, 

is sending Chinese character related to this issue? Chinese character doesn't work with `robot.typeString` on my Windows 10 machine.

I notice that [`keypress.c`](https://github.com/octalmage/robotjs/blob/master/src/keypress.c#L105) is using `keybd_event` to simulate keypress. 

However, I have stumbled upon [a question on stackoverflow](http://stackoverflow.com/questions/3726812/how-to-send-unicode-keys-with-c-keybd-event) about sending unicode with c++ on Windows.

It seems to suggest that [`sendInput`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646310(v=vs.85).aspx) should be used instead of `keybd_event` for sending unicode.

**Comment by dexmendonca** [comment] 2017-03-06 16:36
Same bug on Linux

**Closed** 2017-11-17 16:45 UTC
Labels: bug, mac, ready
