### ISSUE TITLE
Mouse Not Moving As Expected

### ISSUE THREAD

**Issue by rnikoopour** [octalmage/robotjs#238] opened 2016-09-27 05:12 UTC
When using mouseMoveSmooth API, if yPos is a constant and the cursor reaches yPos, the xPos no longer changes.
## Expected Behavior

```
robot.moveMouseSmooth(xPos, 5);
```

When cursor's yPos = 5, xPos should still be able to change.
## Current Behavior

When the cursor's yPos = 5, xPos stops changing
## Steps to Reproduce (for bugs)

Run the below code.

```
'use strict';

const robot = require('robotjs');
const events = require('events');
const eventEmitter = new events.EventEmitter();

eventEmitter.on('mouseMove', moveMouse);

function normalizeMouse(val) {
    return val > 0 ? val : 1;
}

function moveMouse(x, y) {
    const mouse = robot.getMousePos();
    console.log('x:', mouse.x);
    const xPos = normalizeMouse(mouse.x + x)
    const yPos = normalizeMouse(mouse.y + y);
    console.log('xPos:', xPos);
    //console.log('y:', yPos);

    robot.moveMouseSmooth(xPos, 5);
}


function move() {
    eventEmitter.emit('mouseMove', -1, -1);
    setTimeout(move, 1);
}

move();
```
## Context

I was trying to move the mouse but when yPos would go below 0 it would move across the Y axis only until it reached the bottom of the screen then it would continue normal movement.  

I attempted to fix this by setting yPos to 0 if yPos < 0.  When yPos got to 0 the cursor would stop moving the mouse along the X axis
## Your Environment

- RobotJS version: 0.4.4
- Node.js version: 6.2.1
- npm version: 3.9.3
- Operating System: OS X 10.11

**Comment by octalmage** [comment] 2016-10-16 00:08
Hi @rnikoopour, 

Thanks for the great bug report! I'll take a look and see what I can figure out. moveMouseSmooth is a weird function, it might be replaced by #174. Randomization can be applied user-land.

**Comment by SamuraiJack** [comment] 2017-12-01 14:44
Confirmed. I had to implement own algorithm of moving the mouse, otherwise it would end in slightly different point, than intended.

**Comment by octalmage** [comment] 2018-03-12 22:49
mouseMoveSmooth is a strange function anyway. Not only is it "smooth", but it's also a bit random. The code for the function isn't too difficult if someone wants to take a look at resolving this: 

https://github.com/octalmage/robotjs/blob/master/src/mouse.c#L343

**Comment by jfizz** [comment] 2019-03-05 04:58
@SamuraiJack would you mind sharing your changes?

**Comment by SamuraiJack** [comment] 2019-03-05 07:56
@jfizz my code is in the "user land", not in the C++ side. It seems moving the cursor to small distance works fine, but for big distances it fails. So I've implemented own cursor movement between the 2 points, using Bresenham algorithm: https://stackoverflow.com/questions/4672279/bresenham-algorithm-in-javascript?noredirect=1&lq=1

**Comment by oktapodia** [comment] 2019-11-24 17:18
This issue has been closed because it has been inactive for > 180 days.
You may reopen this issue if it has been closed in error.

**Closed by oktapodia** 2019-11-24 17:18 UTC
Labels: bug, ready
